<?php
declare(strict_types=1);
require __DIR__ . '/config.php';
require __DIR__ . '/mailer.php';

header('Content-Type: application/json; charset=utf-8');
header('X-Content-Type-Options: nosniff');
header('Referrer-Policy: same-origin');
session_name('gosharesplit_admin');
session_set_cookie_params(['lifetime'=>0,'path'=>'/','secure'=>(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off'),'httponly'=>true,'samesite'=>'Strict']);
session_start();

if (!is_dir(DATA_DIR) && !mkdir(DATA_DIR,0750,true) && !is_dir(DATA_DIR)) { http_response_code(500); echo json_encode(['error'=>'data_directory_unavailable']); exit; }
function respond(array $p,int $s=200):never{http_response_code($s);echo json_encode($p,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function body():array{$d=json_decode(file_get_contents('php://input')?:'',true);return is_array($d)?$d:[];}
function read_json(string $f,array $default=[]):array{if(!is_file($f))return $default;$fp=fopen($f,'rb');if(!$fp)return $default;flock($fp,LOCK_SH);$raw=stream_get_contents($fp)?:'[]';flock($fp,LOCK_UN);fclose($fp);$d=json_decode($raw,true);return is_array($d)?$d:$default;}
function write_json(string $f,array $d):void{$tmp=$f.'.tmp';$fp=fopen($tmp,'wb');if(!$fp)throw new RuntimeException('write');flock($fp,LOCK_EX);fwrite($fp,json_encode($d,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));fflush($fp);flock($fp,LOCK_UN);fclose($fp);rename($tmp,$f);@chmod($f,0640);}
function clean(string $v,int $m=180):string{return mb_substr(trim(strip_tags($v)),0,$m);}
function uid():string{return bin2hex(random_bytes(12));}
function norm(string $v):string{$v=mb_strtolower(trim($v),'UTF-8');$v=iconv('UTF-8','ASCII//TRANSLIT//IGNORE',$v)?:$v;return preg_replace('/[^a-z0-9]+/','',$v)?:'';}
function now():string{return gmdate(DATE_ATOM);}
function defaults_settings():array{return ['listing_duration_days'=>45,'max_seats'=>20,'recent_featured_count'=>2,'new_badge_hours'=>24,'price_compare_min'=>4,'mail_suspended'=>false,'site_texts'=>['hero_fr'=>'Trouvez facilement une place dans un abonnement partagé','hero_en'=>'Find a spot in a shared subscription','subtitle_fr'=>'Comparez les offres Spliiit, Sharesub et GoSplit au même endroit.','subtitle_en'=>'Compare Spliiit, Sharesub and GoSplit offers in one place.']];}
function defaults_catalog():array{
 $icons=['Streaming vidéo'=>'🍿','Musique'=>'🎵','VPN & Sécurité'=>'🔒','Productivité & Logiciels'=>'💼','IA'=>'🤖','Jeux vidéo'=>'🎮','Presse & Lecture'=>'📰','Bien-être / Sport / Santé'=>'💪','Maison'=>'🏠','Cloud'=>'☁️','Autre'=>'📦'];
 $groups=['Streaming vidéo'=>['Netflix','Disney+','YouTube Premium','Amazon Prime Video','CANAL+','HBO Max','Crunchyroll','Apple TV+','Paramount+','ADN','DAZN','Ligue 1+','Molotov','beIN SPORTS CONNECT'],'Musique'=>['Spotify','Deezer','Apple Music','YouTube Music','Tidal','Qobuz','Amazon Music'],'VPN & Sécurité'=>['NordVPN','Surfshark','ExpressVPN','CyberGhost','Proton VPN','Bitdefender','AdGuard','FastestVPN'],'Productivité & Logiciels'=>['Microsoft 365','Canva','Google One','Dropbox','Notion','Adobe Creative Cloud','GitHub Copilot','Lovable'],'IA'=>['ChatGPT','Google AI / Gemini','Claude','Midjourney','Perplexity','Cursor','Grok','Runway'],'Jeux vidéo'=>['Nintendo Switch Online','Xbox Game Pass','PlayStation Plus','Apple Arcade','Discord Nitro','EA Play','Ubisoft+'],'Presse & Lecture'=>['Le Monde','Le Figaro','Cafeyn','Scribd','Readly','Blinkist','L’Équipe','Mediapart'],'Bien-être / Sport / Santé'=>['Strava','Headspace','Calm','Petit Bambou','Cookidoo','Duolingo','Babbel'],'Maison'=>['Amazon Prime','Cdiscount','Uber One','Deliveroo Plus'],'Cloud'=>['iCloud+','pCloud','MEGA','kDrive'],'Autre'=>['Apple One']];
 $categories=[];$services=[];$pop=100;
 foreach($icons as $name=>$icon){$cid='cat_'.substr(hash('sha256',$name),0,10);$categories[]=['id'=>$cid,'name'=>$name,'icon'=>$icon];foreach($groups[$name]??[] as $service){$services[]=['id'=>'svc_'.substr(hash('sha256',$service),0,12),'name'=>$service,'category_id'=>$cid,'icon'=>$icon,'popularity'=>max(1,$pop--)];}}
 return ['categories'=>$categories,'services'=>$services];
}
function init_data():void{
 foreach(['offers.json','suggestions.json','alerts.json','reports.json'] as $n){$src=LEGACY_DATA_DIR.'/'.$n;$dst=DATA_DIR.'/'.$n;if(is_file($src)&&!is_file($dst))@copy($src,$dst);}
 if(!is_file(SETTINGS_FILE))write_json(SETTINGS_FILE,defaults_settings());
 if(!is_file(CATALOG_FILE))write_json(CATALOG_FILE,defaults_catalog());
 if(!is_file(USERS_FILE))write_json(USERS_FILE,[['id'=>'super','username'=>BOOTSTRAP_SUPER_USERNAME,'password_hash'=>BOOTSTRAP_SUPER_PASSWORD_HASH,'role'=>'super','active'=>true,'permissions'=>[],'created_at'=>now()]]);
 if(!is_file(ACTIVITY_FILE))write_json(ACTIVITY_FILE,[]);
}
init_data();
function current_user():?array{return is_array($_SESSION['user']??null)?$_SESSION['user']:null;}
function require_auth():array{$u=current_user();if(!$u)respond(['error'=>'unauthorized'],401);return $u;}
function csrf(array $d):void{if(empty($_SESSION['csrf'])||!hash_equals((string)$_SESSION['csrf'],(string)($d['csrf']??'')))respond(['error'=>'csrf'],403);}
function can(string $permission):bool{$u=current_user();if(!$u)return false;if(in_array($u['role']??'', ['super','admin'],true))return true;return in_array($permission,$u['permissions']??[],true);}
function need(string $permission):array{$u=require_auth();if(!can($permission))respond(['error'=>'forbidden'],403);return $u;}
function log_action(string $action,array $details=[]):void{$u=current_user();$items=read_json(ACTIVITY_FILE);array_unshift($items,['id'=>uid(),'at'=>now(),'user'=>$u['username']??'système','role'=>$u['role']??'public','action'=>$action,'details'=>$details]);write_json(ACTIVITY_FILE,array_slice($items,0,1000));}
function site_url():string{$cfg=smtp_config();if(!empty($cfg['site_url']))return rtrim((string)$cfg['site_url'],'/');$https=!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off';$host=$_SERVER['HTTP_HOST']??'';return $host?(($https?'https':'http').'://'.$host):'';}
function manage_url(string $token):string{return site_url().'/#/mes-alertes?token='.rawurlencode($token);}
function catalog_enriched():array{$cat=read_json(CATALOG_FILE,defaults_catalog());$alerts=read_json(ALERTS_FILE);$counts=[];foreach($alerts as $a)if(!empty($a['active'])){$k=norm((string)($a['service']??''));$counts[$k]=($counts[$k]??0)+1;}foreach($cat['services'] as &$s)$s['active_alerts']=$counts[norm((string)$s['name'])]??0;unset($s);return $cat;}
function notify_matching_alerts(array $offer):void{$settings=read_json(SETTINGS_FILE,defaults_settings());if(!empty($settings['mail_suspended']))return;$alerts=read_json(ALERTS_FILE);$target=norm((string)($offer['service']??''));$changed=false;foreach($alerts as &$a){if(empty($a['active'])||norm((string)($a['service']??''))!==$target)continue;$sent=is_array($a['notified_offer_ids']??null)?$a['notified_offer_ids']:[];if(in_array((string)$offer['id'],$sent,true))continue;$token=(string)($a['management_token']??$a['token']??'');$content='<p>Une nouvelle offre correspond à ton alerte.</p><p><strong>Service :</strong> '.htmlspecialchars((string)$offer['service']).'<br><strong>Offre :</strong> '.htmlspecialchars((string)($offer['plan']??'')).'<br><strong>Prix :</strong> '.number_format((float)$offer['price'],2,',',' ').' € / mois<br><strong>Places :</strong> '.(int)$offer['seats'].'</p><p><a href="'.htmlspecialchars(manage_url($token),ENT_QUOTES).'">Gérer mes alertes</a></p>';if(send_smtp_mail((string)$a['email'],'Nouvelle offre '.$offer['service'].' sur GoShareSplit',mail_layout('Nouvelle offre disponible 🎉',$content,'Voir l’annonce',site_url()?:'#'))){$sent[]=(string)$offer['id'];$a['notified_offer_ids']=array_values(array_unique($sent));$a['last_notified_at']=now();$a['emails_sent']=((int)($a['emails_sent']??0))+1;$changed=true;}}unset($a);if($changed)write_json(ALERTS_FILE,$alerts);}

$action=$_GET['action']??'list';$method=$_SERVER['REQUEST_METHOD']??'GET';$data=body();
try{
 if($action==='session')respond(['authenticated'=>(bool)current_user(),'csrf'=>$_SESSION['csrf']??null,'user'=>current_user()]);
 if($action==='login'&&$method==='POST'){$users=read_json(USERS_FILE);$username=clean((string)($data['username']??''),80);$password=(string)($data['password']??'');$found=null;foreach($users as $u)if(!empty($u['active'])&&hash_equals((string)$u['username'],$username)&&password_verify($password,(string)$u['password_hash'])){$found=$u;break;}if(!$found){usleep(350000);respond(['error'=>'invalid_credentials'],401);}session_regenerate_id(true);$_SESSION['user']=['id'=>$found['id'],'username'=>$found['username'],'role'=>$found['role'],'permissions'=>$found['permissions']??[]];$_SESSION['csrf']=bin2hex(random_bytes(24));log_action('Connexion');respond(['ok'=>true,'csrf'=>$_SESSION['csrf'],'user'=>$_SESSION['user']]);}
 if($action==='logout'&&$method==='POST'){csrf($data);log_action('Déconnexion');$_SESSION=[];session_destroy();respond(['ok'=>true]);}
 if($action==='public-meta'){respond(['catalog'=>catalog_enriched(),'settings'=>read_json(SETTINGS_FILE,defaults_settings())]);}
 if($action==='list'){$offers=array_values(array_filter(read_json(OFFERS_FILE),fn($o)=>empty($o['hidden'])&&strtotime((string)($o['expires_at']??''))>time()));respond(['offers'=>$offers]);}
 if($action==='create'&&$method==='POST'){$link=filter_var(trim((string)($data['link']??'')),FILTER_VALIDATE_URL);if(!$link)respond(['error'=>'invalid_link'],422);$offers=read_json(OFFERS_FILE);foreach($offers as $o)if(($o['link']??'')===$link)respond(['error'=>'duplicate'],409);$settings=read_json(SETTINGS_FILE,defaults_settings());$service=clean((string)($data['service']??''),80);$plan=clean((string)($data['plan']??''),70);$plan=preg_replace('/^'.preg_quote($service,'/').'\s*[-–—:]?\s*/iu','',$plan)??$plan;$days=max(1,min(365,(int)($settings['listing_duration_days']??45)));$now=new DateTimeImmutable('now',new DateTimeZone('UTC'));$offer=['id'=>uid(),'link'=>$link,'service'=>$service,'service_id'=>clean((string)($data['service_id']??''),80),'plan'=>$plan,'price'=>max(.01,(float)($data['price']??0)),'seats'=>max(1,min((int)($settings['max_seats']??20),(int)($data['seats']??1))),'platform'=>clean((string)($data['platform']??''),30),'category'=>clean((string)($data['category']??'Autre'),60),'icon'=>clean((string)($data['icon']??'📦'),12),'reports_count'=>0,'report_reasons'=>[],'hidden'=>false,'published_at'=>$now->format(DATE_ATOM),'expires_at'=>$now->modify('+'.$days.' days')->format(DATE_ATOM)];if($service===''||$offer['platform']==='')respond(['error'=>'missing_fields'],422);array_unshift($offers,$offer);write_json(OFFERS_FILE,$offers);notify_matching_alerts($offer);respond(['offer'=>$offer],201);}
 if($action==='report'&&$method==='POST'){$id=clean((string)($data['id']??''),64);$visitor=clean((string)($data['visitor']??''),80);$reason=clean((string)($data['reason']??''),40);if(!in_array($reason,['no_seats','invalid_link','wrong_info'],true))respond(['error'=>'invalid_reason'],422);$reports=read_json(REPORTS_FILE);$key=hash('sha256',$id.'|'.$visitor);if(isset($reports[$key]))respond(['error'=>'already_reported'],409);$offers=read_json(OFFERS_FILE);$found=false;foreach($offers as &$o)if(($o['id']??'')===$id){$o['reports_count']=((int)($o['reports_count']??0))+1;$o['report_reasons'][$reason]=((int)($o['report_reasons'][$reason]??0))+1;$found=true;break;}unset($o);if(!$found)respond(['error'=>'not_found'],404);$reports[$key]=['at'=>time(),'reason'=>$reason];write_json(REPORTS_FILE,$reports);write_json(OFFERS_FILE,$offers);respond(['ok'=>true]);}
 if($action==='suggest'&&$method==='POST'){$items=read_json(SUGGESTIONS_FILE);$items[]=['id'=>uid(),'name'=>clean((string)($data['name']??''),80),'category'=>clean((string)($data['category']??'Autre'),60),'website'=>clean((string)($data['website']??''),220),'source'=>clean((string)($data['source']??'menu'),30),'created_at'=>now()];write_json(SUGGESTIONS_FILE,$items);respond(['ok'=>true],201);}
 if($action==='alert'&&$method==='POST'){$email=filter_var(trim((string)($data['email']??'')),FILTER_VALIDATE_EMAIL);$service=clean((string)($data['service']??''),80);if(!$email||$service==='')respond(['error'=>'invalid_alert'],422);$items=read_json(ALERTS_FILE);foreach($items as $e)if(!empty($e['active'])&&strcasecmp((string)$e['email'],(string)$email)===0&&norm((string)$e['service'])===norm($service))respond(['error'=>'duplicate_alert'],409);$management='';foreach($items as $e)if(strcasecmp((string)($e['email']??''),(string)$email)===0){$management=(string)($e['management_token']??'');break;}if($management==='')$management=bin2hex(random_bytes(32));$token=bin2hex(random_bytes(24));$item=['id'=>uid(),'email'=>$email,'service'=>$service,'service_id'=>clean((string)($data['service_id']??''),80),'token'=>$token,'management_token'=>$management,'active'=>true,'notified_offer_ids'=>[],'emails_sent'=>0,'created_at'=>now()];$items[]=$item;write_json(ALERTS_FILE,$items);$content='<p>Ton alerte pour <strong>'.htmlspecialchars($service).'</strong> est active.</p><p><a href="'.htmlspecialchars(manage_url($management),ENT_QUOTES).'">Gérer mes alertes</a></p>';send_smtp_mail((string)$email,'Alerte GoShareSplit activée',mail_layout('Alerte activée ✅',$content,'Voir GoShareSplit',site_url()?:'#'));respond(['ok'=>true],201);}
 if($action==='request-alert-management'&&$method==='POST'){$email=filter_var(trim((string)($data['email']??'')),FILTER_VALIDATE_EMAIL);if(!$email)respond(['error'=>'invalid_email'],422);$items=read_json(ALERTS_FILE);$token='';foreach($items as &$i)if(strcasecmp((string)($i['email']??''),(string)$email)===0){$token=(string)($i['management_token']??'');if($token==='')$token=bin2hex(random_bytes(32));$i['management_token']=$token;}unset($i);if($token!==''){write_json(ALERTS_FILE,$items);send_smtp_mail((string)$email,'Gérer mes alertes GoShareSplit',mail_layout('Gérer mes alertes','<p>Utilise ce lien sécurisé pour gérer tes alertes.</p>','Ouvrir mes alertes',manage_url($token)));}respond(['ok'=>true]);}
 if($action==='manage-alerts'){$token=clean((string)($_GET['token']??''),160);$items=read_json(ALERTS_FILE);$matches=[];$email='';foreach($items as $i)if(hash_equals((string)($i['management_token']??$i['token']??''),$token)){$email=(string)$i['email'];$matches[]=['id'=>$i['id'],'service'=>$i['service'],'active'=>!empty($i['active']),'created_at'=>$i['created_at']??''];}if(!$matches)respond(['error'=>'not_found'],404);$parts=explode('@',$email,2);$masked=mb_substr($parts[0]??'',0,1).'•••@'.($parts[1]??'');respond(['email'=>$masked,'alerts'=>$matches]);}
 if($action==='manage-alert-update'&&$method==='POST'){$token=clean((string)($data['token']??''),160);$id=clean((string)($data['id']??''),64);$op=clean((string)($data['operation']??''),20);$items=read_json(ALERTS_FILE);$found=false;$next=[];foreach($items as $i){if(($i['id']??'')===$id&&hash_equals((string)($i['management_token']??$i['token']??''),$token)){$found=true;if($op==='delete')continue;$i['active']=$op==='enable';$i['updated_at']=now();}$next[]=$i;}if(!$found)respond(['error'=>'not_found'],404);write_json(ALERTS_FILE,array_values($next));respond(['ok'=>true]);}
 if($action==='unsubscribe'&&$method==='POST'){$token=clean((string)($data['token']??''),120);$items=read_json(ALERTS_FILE);$found=false;foreach($items as &$i)if(hash_equals((string)($i['token']??''),$token)){$i['active']=false;$found=true;break;}unset($i);if(!$found)respond(['error'=>'not_found'],404);write_json(ALERTS_FILE,$items);respond(['ok'=>true]);}

 // Administration
 if($action==='admin-dashboard'){require_auth();$offers=read_json(OFFERS_FILE);$alerts=read_json(ALERTS_FILE);$suggestions=read_json(SUGGESTIONS_FILE);$activeOffers=array_values(array_filter($offers,fn($o)=>empty($o['hidden'])&&strtotime((string)($o['expires_at']??''))>time()));$activeAlerts=array_values(array_filter($alerts,fn($a)=>!empty($a['active'])));$alertTop=[];foreach($activeAlerts as $a)$alertTop[$a['service']]=($alertTop[$a['service']]??0)+1;arsort($alertTop);respond(['counts'=>['offers'=>count($activeOffers),'alerts'=>count($alerts),'active_alerts'=>count($activeAlerts),'suggestions'=>count($suggestions),'reports'=>array_sum(array_map(fn($o)=>(int)($o['reports_count']??0),$activeOffers))],'top_alerts'=>array_slice($alertTop,0,10,true)]);}
 if($action==='admin-list'){need('offers.view');respond(['offers'=>read_json(OFFERS_FILE)]);}
 if($action==='admin-update'&&$method==='POST'){need('offers.edit');csrf($data);$offers=read_json(OFFERS_FILE);$found=false;foreach($offers as &$o)if(($o['id']??'')===($data['id']??'')){foreach(['service','plan','category'] as $k)$o[$k]=clean((string)($data[$k]??$o[$k]??''),$k==='plan'?70:100);$o['price']=max(.01,(float)($data['price']??$o['price']));$settings=read_json(SETTINGS_FILE,defaults_settings());$o['seats']=max(0,min((int)($settings['max_seats']??20),(int)($data['seats']??$o['seats'])));$duration=max(1,min(365,(int)($data['duration_days']??45)));$o['expires_at']=(new DateTimeImmutable('now',new DateTimeZone('UTC')))->modify('+'.$duration.' days')->format(DATE_ATOM);if(!empty($data['reset_reports'])){$o['reports_count']=0;$o['report_reasons']=[];}$o['updated_at']=now();$found=true;break;}unset($o);if(!$found)respond(['error'=>'not_found'],404);write_json(OFFERS_FILE,$offers);log_action('Annonce modifiée',['id'=>$data['id']??'']);respond(['ok'=>true]);}
 if($action==='admin-delete'&&$method==='POST'){need('offers.delete');csrf($data);$id=(string)($data['id']??'');write_json(OFFERS_FILE,array_values(array_filter(read_json(OFFERS_FILE),fn($o)=>($o['id']??'')!==$id)));log_action('Annonce supprimée',['id'=>$id]);respond(['ok'=>true]);}
 if($action==='admin-suggestions'){need('suggestions.view');respond(['suggestions'=>array_reverse(read_json(SUGGESTIONS_FILE))]);}
 if($action==='admin-suggestion-delete'&&$method==='POST'){need('suggestions.manage');csrf($data);$id=(string)($data['id']??'');write_json(SUGGESTIONS_FILE,array_values(array_filter(read_json(SUGGESTIONS_FILE),fn($o)=>($o['id']??'')!==$id)));log_action('Suggestion supprimée',['id'=>$id]);respond(['ok'=>true]);}
 if($action==='admin-catalog'){need('catalog.view');respond(catalog_enriched());}
 if($action==='admin-category-save'&&$method==='POST'){need('categories.edit');csrf($data);$cat=read_json(CATALOG_FILE,defaults_catalog());$id=clean((string)($data['id']??''),80);$name=clean((string)($data['name']??''),60);$icon=clean((string)($data['icon']??'📦'),12);if($name==='')respond(['error'=>'missing_name'],422);if($id===''){$id=uid();$cat['categories'][]=['id'=>$id,'name'=>$name,'icon'=>$icon];}else foreach($cat['categories'] as &$c)if($c['id']===$id){$c['name']=$name;$c['icon']=$icon;}unset($c);write_json(CATALOG_FILE,$cat);log_action('Catégorie enregistrée',['name'=>$name]);respond(['ok'=>true,'id'=>$id]);}
 if($action==='admin-category-delete'&&$method==='POST'){need('categories.delete');csrf($data);$id=(string)($data['id']??'');$target=(string)($data['target_id']??'');$cat=read_json(CATALOG_FILE,defaults_catalog());if($id===$target)respond(['error'=>'invalid_target'],422);$exists=false;foreach($cat['categories'] as $c)if($c['id']===$target)$exists=true;if(!$exists)respond(['error'=>'invalid_target'],422);$cat['categories']=array_values(array_filter($cat['categories'],fn($c)=>$c['id']!==$id));foreach($cat['services'] as &$s)if($s['category_id']===$id)$s['category_id']=$target;unset($s);write_json(CATALOG_FILE,$cat);log_action('Catégorie supprimée',['id'=>$id]);respond(['ok'=>true]);}
 if($action==='admin-service-save'&&$method==='POST'){need('services.edit');csrf($data);$cat=read_json(CATALOG_FILE,defaults_catalog());$id=clean((string)($data['id']??''),80);$item=['name'=>clean((string)($data['name']??''),80),'category_id'=>clean((string)($data['category_id']??''),80),'icon'=>clean((string)($data['icon']??'📦'),12),'popularity'=>max(0,min(999,(int)($data['popularity']??0)))];if($item['name']===''||$item['category_id']==='')respond(['error'=>'missing_fields'],422);if($id===''){$id=uid();$cat['services'][]=['id'=>$id]+$item;}else foreach($cat['services'] as &$s)if($s['id']===$id)$s=array_merge($s,$item);unset($s);write_json(CATALOG_FILE,$cat);log_action('Service enregistré',['name'=>$item['name']]);respond(['ok'=>true,'id'=>$id]);}
 if($action==='admin-service-delete'&&$method==='POST'){need('services.delete');csrf($data);$id=(string)($data['id']??'');$cat=read_json(CATALOG_FILE,defaults_catalog());$cat['services']=array_values(array_filter($cat['services'],fn($s)=>$s['id']!==$id));write_json(CATALOG_FILE,$cat);log_action('Service supprimé',['id'=>$id]);respond(['ok'=>true]);}
 if($action==='admin-alerts'){need('alerts.view');respond(['alerts'=>array_reverse(read_json(ALERTS_FILE)),'mail_suspended'=>(bool)(read_json(SETTINGS_FILE,defaults_settings())['mail_suspended']??false)]);}
 if($action==='admin-alert-update'&&$method==='POST'){need('alerts.manage');csrf($data);$items=read_json(ALERTS_FILE);$id=(string)($data['id']??'');$op=(string)($data['operation']??'');$next=[];foreach($items as $i){if(($i['id']??'')===$id){if($op==='delete')continue;$i['active']=$op==='enable';}$next[]=$i;}write_json(ALERTS_FILE,array_values($next));log_action('Alerte '.$op,['id'=>$id]);respond(['ok'=>true]);}
 if($action==='admin-settings'){require_auth();respond(['settings'=>read_json(SETTINGS_FILE,defaults_settings())]);}
 if($action==='admin-settings-save'&&$method==='POST'){need('settings.edit');csrf($data);$old=read_json(SETTINGS_FILE,defaults_settings());$allowed=['listing_duration_days','max_seats','recent_featured_count','new_badge_hours','price_compare_min','mail_suspended','site_texts'];foreach($allowed as $k)if(array_key_exists($k,$data))$old[$k]=$data[$k];$old['listing_duration_days']=max(1,min(365,(int)$old['listing_duration_days']));$old['max_seats']=max(1,min(100,(int)$old['max_seats']));$old['recent_featured_count']=max(0,min(10,(int)$old['recent_featured_count']));$old['new_badge_hours']=max(1,min(168,(int)$old['new_badge_hours']));$old['price_compare_min']=max(2,min(20,(int)$old['price_compare_min']));write_json(SETTINGS_FILE,$old);log_action('Paramètres modifiés');respond(['ok'=>true]);}
 if($action==='admin-users'){require_auth();$u=current_user();$users=read_json(USERS_FILE);$safe=[];foreach($users as $x){if(($u['role']??'')==='admin'&&($x['role']??'')!=='moderator')continue;unset($x['password_hash']);$safe[]=$x;}respond(['users'=>$safe]);}
 if($action==='admin-user-save'&&$method==='POST'){$actor=require_auth();csrf($data);$users=read_json(USERS_FILE);$id=clean((string)($data['id']??''),80);$role=clean((string)($data['role']??'moderator'),20);if($actor['role']==='admin'&&$role!=='moderator')respond(['error'=>'forbidden'],403);if($actor['role']==='moderator')respond(['error'=>'forbidden'],403);if($role==='super')respond(['error'=>'forbidden'],403);$username=clean((string)($data['username']??''),80);$password=(string)($data['password']??'');$permissions=is_array($data['permissions']??null)?array_values($data['permissions']):[];if($id===''){if($username===''||strlen($password)<10)respond(['error'=>'weak_credentials'],422);foreach($users as $x)if(strcasecmp($x['username'],$username)===0)respond(['error'=>'duplicate_user'],409);$users[]=['id'=>uid(),'username'=>$username,'password_hash'=>password_hash($password,PASSWORD_DEFAULT),'role'=>$role,'active'=>true,'permissions'=>$permissions,'created_at'=>now()];}else{foreach($users as &$x)if($x['id']===$id){if($x['role']==='super'||($actor['role']==='admin'&&$x['role']!=='moderator'))respond(['error'=>'forbidden'],403);$x['username']=$username?:$x['username'];$x['role']=$role;$x['active']=array_key_exists('active',$data)?(bool)$data['active']:$x['active'];$x['permissions']=$permissions;if($password!==''){$x['password_hash']=password_hash($password,PASSWORD_DEFAULT);}break;}unset($x);}write_json(USERS_FILE,$users);log_action('Utilisateur enregistré',['username'=>$username,'role'=>$role]);respond(['ok'=>true]);}
 if($action==='admin-user-delete'&&$method==='POST'){$actor=require_auth();csrf($data);$id=(string)($data['id']??'');$users=read_json(USERS_FILE);$target=null;foreach($users as $x)if($x['id']===$id)$target=$x;if(!$target||$target['role']==='super'||($actor['role']==='admin'&&$target['role']!=='moderator')||$actor['role']==='moderator')respond(['error'=>'forbidden'],403);write_json(USERS_FILE,array_values(array_filter($users,fn($x)=>$x['id']!==$id)));log_action('Utilisateur supprimé',['username'=>$target['username']]);respond(['ok'=>true]);}
 if($action==='admin-activity'){require_auth();respond(['activity'=>read_json(ACTIVITY_FILE)]);}
 if($action==='admin-backup-export'){need('backups.manage');$payload=['version'=>2,'created_at'=>now(),'data'=>['offers'=>read_json(OFFERS_FILE),'suggestions'=>read_json(SUGGESTIONS_FILE),'alerts'=>read_json(ALERTS_FILE),'catalog'=>read_json(CATALOG_FILE,defaults_catalog()),'settings'=>read_json(SETTINGS_FILE,defaults_settings()),'activity'=>read_json(ACTIVITY_FILE)]];$json=json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$compressed=gzdeflate($json,9);$encoded=rtrim(strtr(base64_encode($compressed),'+/','-_'),'=');$sig=hash_hmac('sha256',$encoded,BACKUP_SECRET);respond(['backup'=>'GSS2:'.$encoded.'.'.$sig,'summary'=>['offers'=>count($payload['data']['offers']),'alerts'=>count($payload['data']['alerts']),'services'=>count($payload['data']['catalog']['services']),'categories'=>count($payload['data']['catalog']['categories'])]]);}
 if($action==='admin-backup-import'&&$method==='POST'){need('backups.manage');csrf($data);$raw=trim((string)($data['backup']??''));if(!str_starts_with($raw,'GSS2:'))respond(['error'=>'invalid_backup'],422);$parts=explode('.',substr($raw,5),2);if(count($parts)!==2||!hash_equals(hash_hmac('sha256',$parts[0],BACKUP_SECRET),$parts[1]))respond(['error'=>'invalid_signature'],422);$b64=strtr($parts[0],'-_','+/');$b64.=str_repeat('=',(4-strlen($b64)%4)%4);$json=gzinflate(base64_decode($b64,true)?:'');$payload=json_decode($json?:'',true);if(!is_array($payload['data']??null))respond(['error'=>'invalid_backup'],422);$d=$payload['data'];foreach(['offers'=>OFFERS_FILE,'suggestions'=>SUGGESTIONS_FILE,'alerts'=>ALERTS_FILE,'catalog'=>CATALOG_FILE,'settings'=>SETTINGS_FILE,'activity'=>ACTIVITY_FILE] as $k=>$f)if(is_array($d[$k]??null))write_json($f,$d[$k]);log_action('Sauvegarde restaurée');respond(['ok'=>true]);}
 respond(['error'=>'not_found'],404);
}catch(Throwable $e){respond(['error'=>'server_error','detail'=>$e->getMessage()],500);}
