import { useEffect, useMemo, useState } from 'react'
import { Activity, Bell, Boxes, ExternalLink, FolderTree, LayoutDashboard, LogOut, Pencil, Search, Save, Settings, Shield, Trash2, Users, X, DatabaseBackup, Lightbulb, Flag, Eraser } from 'lucide-react'
import { adminGet, adminLogin, adminLogout, adminPost, deleteOffer, deleteSuggestion, getAdminSession, listAdminOffers, listAdminSuggestions, updateOffer } from '../lib/store'

const tabs=[['dashboard','Tableau de bord',LayoutDashboard],['offers','Annonces',Boxes],['suggestions','Suggestions',Lightbulb],['categories','Catégories',FolderTree],['services','Services',Shield],['alerts','Alertes',Bell],['users','Utilisateurs',Users],['settings','Paramètres',Settings],['backup','Sauvegarde',DatabaseBackup],['activity','Activité',Activity]]

const iconChoices = ['✨','🔗','🌐','📦','🎬','🎵','🎮','🛡️','🔒','💼','🤖','📰','☁️','📺','🎧','📚','⚽','🍿']
const perms=['offers.view','offers.edit','offers.delete','suggestions.view','suggestions.manage','catalog.view','categories.edit','categories.delete','services.edit','services.delete','alerts.view','alerts.manage']
const input='w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 outline-none focus:border-emerald-400'
const btn='rounded-xl border border-slate-700 px-3 py-2 text-sm font-bold hover:bg-slate-800'

export default function AdminPage(){
 const [session,setSession]=useState(null),[login,setLogin]=useState({username:'',password:''}),[error,setError]=useState(''),[tab,setTab]=useState('dashboard'),[data,setData]=useState({}),[editing,setEditing]=useState(null),[backup,setBackup]=useState(''),[backupSections,setBackupSections]=useState(['offers','suggestions','alerts','catalog','settings','activity'])
 useEffect(()=>{getAdminSession().then(setSession)},[])
 async function load(name=tab){if(!session?.authenticated)return;const actions={dashboard:'admin-dashboard',offers:'admin-list',suggestions:'admin-suggestions',categories:'admin-catalog',services:'admin-catalog',alerts:'admin-alerts',users:'admin-users',settings:'admin-settings',activity:'admin-activity'};if(actions[name]){const result=await adminGet(actions[name]);setData(d=>({...d,[name]:result}))}}
 useEffect(()=>{load(tab)},[tab,session?.authenticated])
 async function doLogin(e){e.preventDefault();try{const r=await adminLogin(login.username,login.password);setSession({authenticated:true,csrf:r.csrf,user:r.user})}catch{setError('Identifiants incorrects.')}}
 async function post(action,payload={}){await adminPost(action,payload,session.csrf);await load(tab)}
 async function openOfferEditor(offer){
   let catalog=data.services
   if(!catalog?.services){
     catalog=await adminGet('admin-catalog')
     setData(d=>({...d,services:catalog}))
   }
   setEditing({...offer,duration_days:45})
 }
 if(session===null)return <div className="grid min-h-screen place-items-center bg-[#06101d] text-white">Chargement…</div>
 if(!session.authenticated)return <div className="grid min-h-screen place-items-center bg-[#06101d] p-4 text-white"><form onSubmit={doLogin} className="relative w-full max-w-md rounded-3xl border border-slate-700 bg-slate-900 p-7 shadow-2xl"><a href="/#/" className="absolute right-5 top-5 rounded-lg p-2 text-slate-400 hover:bg-slate-800 hover:text-white"><X size={20}/></a><h1 className="mb-6 text-2xl font-black">Connexion administration</h1><div className="space-y-4"><input className={input} placeholder="Identifiant" value={login.username} onChange={e=>setLogin({...login,username:e.target.value})}/><input type="password" className={input} placeholder="Mot de passe" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/>{error&&<p className="text-red-400">{error}</p>}<button className="w-full rounded-xl bg-emerald-400 py-3 font-black text-slate-950">Se connecter</button></div></form></div>
 const user=session.user||{}
 return <div className="min-h-screen bg-[#07101b] text-slate-100"><header className="border-b border-slate-800 bg-slate-950/80"><div className="mx-auto flex max-w-7xl items-center gap-3 px-4 py-4"><h1 className="text-xl font-black">GoShareSplit — Administration</h1><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs font-bold text-emerald-300">{user.username} · {user.role}</span><a href="/#/" className="ml-auto rounded-xl border border-slate-700 px-3 py-2 text-sm font-bold">Voir le site</a><button onClick={async()=>{await adminLogout(session.csrf);location.reload()}} className={btn}><LogOut size={17}/></button></div></header><div className="mx-auto grid max-w-7xl gap-5 px-4 py-6 lg:grid-cols-[220px_1fr]"><aside className="h-fit rounded-2xl border border-slate-800 bg-slate-900/70 p-2">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-bold ${tab===id?'bg-emerald-400 text-slate-950':'hover:bg-slate-800'}`}><Icon size={17}/>{label}</button>)}</aside><main className="min-w-0 rounded-2xl border border-slate-800 bg-slate-900/55 p-5">{tab==='dashboard'&&<Dashboard data={data.dashboard}/>} {tab==='offers'&&<Offers items={data.offers?.offers||[]} onEdit={openOfferEditor} onDelete={async id=>{if(confirm('Supprimer cette annonce ?')){await deleteOffer(id,session.csrf);load('offers')}}}/>} {tab==='suggestions'&&<Suggestions items={data.suggestions?.suggestions||[]} onDelete={async id=>{await deleteSuggestion(id,session.csrf);load('suggestions')}}/>} {tab==='categories'&&<Categories data={data.categories} post={post} canEditEmoji={['super','admin'].includes(user.role)}/>} {tab==='services'&&<Services data={data.services} post={post} canEditEmoji={['super','admin'].includes(user.role)}/>} {tab==='alerts'&&<Alerts data={data.alerts} post={post}/>} {tab==='users'&&<UserManager data={data.users} role={user.role} post={post}/>} {tab==='settings'&&<SettingsPanel data={data.settings} post={post}/>} {tab==='backup'&&<Backup backup={backup} setBackup={setBackup} sections={backupSections} setSections={setBackupSections} exportIt={async()=>{const r=await adminPost('admin-backup-export',{sections:backupSections},session.csrf);setBackup(r.backup)}} importIt={async()=>{if(confirm('Restaurer cette sauvegarde ?'))await post('admin-backup-import',{backup})}}/>} {tab==='activity'&&<ActivityPanel data={data.activity} isSuper={user.role==='super'} onDelete={async id=>{if(confirm('Supprimer cette activité ?'))await post('admin-activity-delete',{id})}} onClear={async()=>{if(confirm('Vider définitivement tout le journal d’activité ?'))await post('admin-activity-clear')}}/>}</main></div>
 {editing&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4"><form onSubmit={async e=>{e.preventDefault();await updateOffer(editing.id,{...editing,price:Number(editing.price),seats:Number(editing.seats)},session.csrf);setEditing(null);load('offers')}} className="w-full max-w-xl rounded-2xl border border-slate-700 bg-slate-900 p-6"><div className="mb-4 flex justify-between"><div><h2 className="text-xl font-black">Modifier l’annonce</h2><p className="mt-1 text-sm text-slate-400">Annonce : <b className="text-white">{editing.service}{editing.plan?` — ${editing.plan}`:''}</b></p></div><button type="button" onClick={()=>setEditing(null)}><X/></button></div><div className="grid gap-3"><label><span className="mb-1 block text-sm font-bold text-slate-300">Service</span><input list="admin-service-options" autoComplete="off" className={input} value={editing.service} onChange={e=>setEditing({...editing,service:e.target.value})}/><datalist id="admin-service-options">{(data.services?.services||[]).map(service=><option key={service.id||service.name} value={service.name}/>)}</datalist><span className="mt-1 block text-xs text-slate-500">Commence à écrire ou sélectionne un service existant dans la liste.</span></label><label><span className="mb-1 block text-sm font-bold text-slate-300">Offre / formule</span><input maxLength={70} className={input} value={editing.plan||''} onChange={e=>setEditing({...editing,plan:e.target.value})}/></label><div className="grid grid-cols-2 gap-3"><label><span className="mb-1 block text-sm font-bold text-slate-300">Prix mensuel (€)</span><input type="number" step="0.01" className={input} value={editing.price} onChange={e=>setEditing({...editing,price:e.target.value})}/></label><label><span className="mb-1 block text-sm font-bold text-slate-300">Places disponibles</span><input type="number" max="20" className={input} value={editing.seats} onChange={e=>setEditing({...editing,seats:e.target.value})}/></label></div><label><span className="mb-1 block text-sm font-bold text-slate-300">Durée avant expiration (jours)</span><input type="number" className={input} value={editing.duration_days} onChange={e=>setEditing({...editing,duration_days:e.target.value})}/></label><label className="flex gap-2"><input type="checkbox" checked={!!editing.reset_reports} onChange={e=>setEditing({...editing,reset_reports:e.target.checked})}/>Réinitialiser les signalements</label><button className="rounded-xl bg-emerald-400 py-3 font-black text-slate-950">Enregistrer les modifications</button></div></form></div>}
 </div>
}
function Dashboard({data}){const c=data?.counts||{};return <><h2 className="mb-5 text-2xl font-black">Tableau de bord</h2><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[['Annonces',c.offers],['Alertes actives',c.active_alerts],['Suggestions',c.suggestions],['Signalements',c.reports],['Alertes totales',c.alerts]].map(([l,v])=><div key={l} className="rounded-2xl border border-slate-800 bg-slate-950/50 p-4"><p className="text-sm text-slate-400">{l}</p><p className="mt-2 text-3xl font-black">{v??0}</p></div>)}</div><h3 className="mb-3 mt-7 font-black">Services les plus recherchés</h3><div className="grid gap-2">{Object.entries(data?.top_alerts||{}).map(([k,v])=><div key={k} className="flex justify-between rounded-xl bg-slate-950/50 px-4 py-3"><span>{k}</span><b>{v} alertes</b></div>)}</div></>}
function Offers({items,onEdit,onDelete}){
 const [search,setSearch]=useState(''),[category,setCategory]=useState('Toutes'),[platform,setPlatform]=useState('Toutes'),[sort,setSort]=useState('newest')
 const categories=useMemo(()=>['Toutes',...Array.from(new Set(items.map(o=>o.category||'Autre'))).sort((a,b)=>a.localeCompare(b,'fr'))],[items])
 const platforms=useMemo(()=>['Toutes',...Array.from(new Set(items.map(o=>o.platform).filter(Boolean))).sort((a,b)=>a.localeCompare(b,'fr'))],[items])
 const filtered=useMemo(()=>{
   const q=search.trim().toLocaleLowerCase('fr')
   const result=items.filter(o=>(category==='Toutes'||(o.category||'Autre')===category)&&(platform==='Toutes'||o.platform===platform)&&(!q||`${o.service} ${o.plan||''} ${o.category||''} ${o.platform||''} ${o.link||''}`.toLocaleLowerCase('fr').includes(q)))
   return [...result].sort((a,b)=>{
     if(sort==='oldest')return new Date(a.published_at||0)-new Date(b.published_at||0)
     if(sort==='price-asc')return Number(a.price||0)-Number(b.price||0)
     if(sort==='price-desc')return Number(b.price||0)-Number(a.price||0)
     if(sort==='seats')return Number(b.seats||0)-Number(a.seats||0)
     if(sort==='reports')return Number(b.reports_count||0)-Number(a.reports_count||0)
     if(sort==='category')return (a.category||'Autre').localeCompare(b.category||'Autre','fr')||(a.service||'').localeCompare(b.service||'','fr')
     return new Date(b.published_at||0)-new Date(a.published_at||0)
   })
 },[items,search,category,platform,sort])
 const reset=()=>{setSearch('');setCategory('Toutes');setPlatform('Toutes');setSort('newest')}
 return <><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-2xl font-black">Annonces</h2><p className="mt-1 text-sm text-slate-400">{filtered.length} annonce{filtered.length>1?'s':''} affichée{filtered.length>1?'s':''} sur {items.length}</p></div><button type="button" onClick={reset} className={btn}>Réinitialiser les filtres</button></div>
 <div className="mb-5 grid gap-3 rounded-2xl border border-slate-800 bg-slate-950/40 p-4 md:grid-cols-2 xl:grid-cols-[1.4fr_1fr_1fr_1fr]">
   <label className="relative"><span className="mb-1 block text-xs font-bold text-slate-400">Recherche</span><Search className="absolute bottom-3 left-3 text-slate-500" size={17}/><input className={`${input} pl-10`} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Service, formule, lien…"/></label>
   <label><span className="mb-1 block text-xs font-bold text-slate-400">Catégorie</span><select className={input} value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label>
   <label><span className="mb-1 block text-xs font-bold text-slate-400">Plateforme</span><select className={input} value={platform} onChange={e=>setPlatform(e.target.value)}>{platforms.map(p=><option key={p}>{p}</option>)}</select></label>
   <label><span className="mb-1 block text-xs font-bold text-slate-400">Trier par</span><select className={input} value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Plus récentes</option><option value="oldest">Plus anciennes</option><option value="category">Catégorie</option><option value="price-asc">Prix croissant</option><option value="price-desc">Prix décroissant</option><option value="seats">Nombre de places</option><option value="reports">Plus signalées</option></select></label>
 </div>
 {filtered.length===0?<div className="rounded-2xl border border-dashed border-slate-700 py-14 text-center text-slate-400">Aucune annonce ne correspond aux filtres sélectionnés.</div>:<div className="grid gap-3">
 {filtered.map(o=>{const remaining=Math.max(0,Math.ceil((new Date(o.expires_at).getTime()-Date.now())/86400000));return <article key={o.id} className="rounded-2xl border border-slate-800 bg-slate-950/45 p-4 transition hover:border-slate-700"><div className="grid gap-4 xl:grid-cols-[minmax(0,1.5fr)_repeat(3,minmax(100px,.45fr))_auto] xl:items-center">
   <div className="flex min-w-0 items-start gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-slate-800 text-xl">{o.icon||'📦'}</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate font-black">{o.service}</h3>{o.plan&&<span className="truncate text-sm text-slate-400">— {o.plan}</span>}</div><div className="mt-1 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-slate-800 px-2 py-1">{o.category||'Autre'}</span><span className="rounded-full bg-slate-800 px-2 py-1">{o.platform||'Plateforme inconnue'}</span>{remaining<=7&&<span className="rounded-full bg-orange-400/10 px-2 py-1 font-bold text-orange-300">{remaining} j restants</span>}</div><a href={o.link} target="_blank" rel="noreferrer" className="mt-2 inline-flex max-w-full items-center gap-1 truncate text-xs text-sky-300 hover:underline">{o.link}<ExternalLink size={12}/></a></div></div>
   <div><p className="text-xs text-slate-500">Prix</p><p className="font-black text-emerald-300">{Number(o.price||0).toLocaleString('fr-FR',{style:'currency',currency:'EUR'})}</p></div>
   <div><p className="text-xs text-slate-500">Places</p><p className="font-bold">{o.seats||0}</p></div>
   <div><p className="text-xs text-slate-500">Signalements</p><p className={`flex items-center gap-1 font-bold ${Number(o.reports_count||0)>0?'text-red-300':''}`}><Flag size={14}/>{o.reports_count||0}</p></div>
   <div className="flex gap-2 xl:justify-end"><button onClick={()=>onEdit(o)} className={btn} title="Modifier l’annonce"><Pencil size={16}/></button><button onClick={()=>onDelete(o.id)} className="rounded-xl border border-red-400/40 bg-red-400/10 px-3 py-2 text-red-300 hover:bg-red-400 hover:text-white" title="Supprimer l’annonce"><Trash2 size={16}/></button></div>
 </div>{o.report_reasons&&Number(o.reports_count||0)>0&&<p className="mt-3 border-t border-slate-800 pt-3 text-xs text-slate-400">Plus de places : {o.report_reasons.no_seats||0} · Lien invalide : {o.report_reasons.invalid_link||0} · Informations erronées : {o.report_reasons.wrong_info||0}</p>}</article>})}
 </div>}</>
}
function Suggestions({items,onDelete}){return <><h2 className="mb-4 text-2xl font-black">Suggestions</h2><div className="space-y-3">{items.map(s=><div key={s.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-slate-800 p-4"><b>{s.name}</b><span>{s.category}</span><span className="break-all text-emerald-300">{s.website||'Aucune URL'}</span><button onClick={()=>onDelete(s.id)} className={`${btn} ml-auto`}><Trash2 size={16}/></button></div>)}</div></>}
function Categories({data,post,canEditEmoji}){const [f,setF]=useState({id:'',name:'',icon:'📦'});const reset=()=>setF({id:'',name:'',icon:'📦'});return <><div className="mb-4 flex items-end justify-between gap-3"><div><h2 className="text-2xl font-black">Catégories</h2>{f.id&&<p className="mt-1 text-sm text-emerald-300">Modification de : <b>{f.name}</b></p>}</div>{f.id&&<button type="button" onClick={reset} className={btn}>Annuler la modification</button>}</div><form onSubmit={async e=>{e.preventDefault();await post('admin-category-save',f);reset()}} className={`mb-5 grid gap-3 ${canEditEmoji?'sm:grid-cols-[120px_1fr_auto]':'sm:grid-cols-[1fr_auto]'}`}>{canEditEmoji&&<label><span className="mb-1 block text-xs font-bold text-slate-400">Emoji</span><input className={input} maxLength={12} placeholder="📦" value={f.icon||''} onChange={e=>setF({...f,icon:e.target.value})}/></label>}<label><span className="mb-1 block text-xs font-bold text-slate-400">Nom</span><input className={input} placeholder="Ex. Streaming vidéo" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><button className="rounded-xl bg-emerald-400 px-4 font-black text-slate-950">Enregistrer</button></form><div className="space-y-2">{data?.categories?.map(c=><div key={c.id} className="flex items-center gap-3 rounded-xl border border-slate-800 p-3"><span className="text-2xl">{c.icon||'📦'}</span><b>{c.name}</b><button onClick={()=>setF(c)} className={`${btn} ml-auto`}><Pencil size={15}/></button><button onClick={async()=>{const target=prompt('ID de la catégorie de destination (copie-le dans la liste). Les services seront déplacés.');if(target)await post('admin-category-delete',{id:c.id,target_id:target})}} className={btn}><Trash2 size={15}/></button><code className="text-[10px] text-slate-500">{c.id}</code></div>)}</div></>}
function Services({data,post,canEditEmoji}){const [f,setF]=useState({id:'',name:'',category_id:'',icon:'',popularity:0});const reset=()=>setF({id:'',name:'',category_id:'',icon:'',popularity:0});const edit=s=>setF({...s,icon:s.custom_icon||''});return <><div className="mb-4 flex items-end justify-between gap-3"><div><h2 className="text-2xl font-black">Services</h2>{f.id&&<p className="mt-1 text-sm text-emerald-300">Modification de : <b>{f.name}</b></p>}</div>{f.id&&<button type="button" onClick={reset} className={btn}>Annuler la modification</button>}</div><form onSubmit={async e=>{e.preventDefault();await post('admin-service-save',f);reset()}} className={`mb-5 grid gap-3 ${canEditEmoji?'md:grid-cols-4':'md:grid-cols-3'}`}><label><span className="mb-1 block text-xs font-bold text-slate-400">Nom du service</span><input className={input} placeholder="Ex. Crunchyroll" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label><span className="mb-1 block text-xs font-bold text-slate-400">Catégorie</span><select className={input} value={f.category_id} onChange={e=>setF({...f,category_id:e.target.value})}><option value="">Choisir une catégorie</option>{data?.categories?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{canEditEmoji&&<label><span className="mb-1 block text-xs font-bold text-slate-400">Emoji</span><input className={input} placeholder="Vide = emoji de la catégorie" maxLength={12} value={f.icon||''} onChange={e=>setF({...f,icon:e.target.value})}/></label>}<label><span className="mb-1 block text-xs font-bold text-slate-400">Popularité</span><input type="number" className={input} placeholder="0 à 999" value={f.popularity} onChange={e=>setF({...f,popularity:e.target.value})}/></label><button className={`rounded-xl bg-emerald-400 px-4 py-3 font-black text-slate-950 ${canEditEmoji?'md:col-span-4':'md:col-span-3'}`}>{f.id?'Enregistrer les modifications':'Ajouter le service'}</button></form><div className="space-y-2">{[...(data?.services||[])].sort((a,b)=>{const ai=(data?.categories||[]).findIndex(c=>c.id===a.category_id),bi=(data?.categories||[]).findIndex(c=>c.id===b.category_id);return ai-bi||a.name.localeCompare(b.name,'fr')}).map(s=><div key={s.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-slate-800 p-3"><span className="text-xl">{s.icon||'📦'}</span><b>{s.name}</b><span className="text-slate-400">Popularité {s.popularity} · {s.active_alerts||0} alertes</span><button onClick={()=>edit(s)} className={`${btn} ml-auto`} title={`Modifier ${s.name}`}><Pencil size={15}/></button><button onClick={()=>post('admin-service-delete',{id:s.id})} className={btn} title={`Supprimer ${s.name}`}><Trash2 size={15}/></button></div>)}</div></>}
function Alerts({data,post}){return <><div className="mb-4 flex items-center"><h2 className="text-2xl font-black">Alertes</h2><button onClick={()=>post('admin-settings-save',{mail_suspended:!data?.mail_suspended})} className={`${btn} ml-auto`}>{data?.mail_suspended?'Réactiver tous les mails':'Suspendre tous les mails'}</button></div><div className="space-y-2">{data?.alerts?.map(a=><div key={a.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-slate-800 p-3"><b>{a.service}</b><span>{a.email}</span><span className={a.active?'text-emerald-300':'text-orange-300'}>{a.active?'Active':'Désactivée'}</span><span>{a.emails_sent||0} mails</span><div className="ml-auto flex gap-2"><button onClick={()=>post('admin-alert-update',{id:a.id,operation:a.active?'disable':'enable'})} className={btn}>{a.active?'Désactiver':'Réactiver'}</button><button onClick={()=>post('admin-alert-update',{id:a.id,operation:'delete'})} className={btn}><Trash2 size={15}/></button></div></div>)}</div></>}
function UserManager({data,role,post}){const [f,setF]=useState({id:'',username:'',password:'',role:'moderator',active:true,permissions:[]});return <><h2 className="mb-4 text-2xl font-black">Utilisateurs</h2>{role!=='moderator'&&<form onSubmit={async e=>{e.preventDefault();await post('admin-user-save',f);setF({id:'',username:'',password:'',role:'moderator',active:true,permissions:[]})}} className="mb-5 space-y-3 rounded-xl border border-slate-800 p-4"><div className="grid gap-3 sm:grid-cols-3"><input className={input} placeholder="Identifiant" value={f.username} onChange={e=>setF({...f,username:e.target.value})}/><input className={input} type="password" placeholder="Mot de passe (10 caractères min.)" value={f.password} onChange={e=>setF({...f,password:e.target.value})}/><select className={input} value={f.role} onChange={e=>setF({...f,role:e.target.value})}><option value="moderator">Modérateur</option>{role==='super'&&<option value="admin">Administrateur</option>}</select></div>{f.role==='moderator'&&<div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{perms.map(p=><label key={p} className="flex gap-2 text-sm"><input type="checkbox" checked={f.permissions.includes(p)} onChange={e=>setF({...f,permissions:e.target.checked?[...f.permissions,p]:f.permissions.filter(x=>x!==p)})}/>{p}</label>)}</div>}<button className="rounded-xl bg-emerald-400 px-4 py-2 font-black text-slate-950">Enregistrer</button></form>}<div className="space-y-2">{data?.users?.map(u=><div key={u.id} className="flex items-center gap-3 rounded-xl border border-slate-800 p-3"><b>{u.username}</b><span>{u.role}</span><span>{u.active?'Actif':'Désactivé'}</span>{u.role!=='super'&&<><button onClick={()=>setF({...u,password:''})} className={`${btn} ml-auto`}><Pencil size={15}/></button><button onClick={()=>post('admin-user-delete',{id:u.id})} className={btn}><Trash2 size={15}/></button></>}</div>)}</div></>}
function SettingsPanel({data,post}){const [s,setS]=useState(null);useEffect(()=>{if(data?.settings)setS(data.settings)},[data]);if(!s)return <p>Chargement…</p>;return <><h2 className="mb-4 text-2xl font-black">Paramètres</h2><form onSubmit={e=>{e.preventDefault();post('admin-settings-save',s)}} className="grid gap-4 max-w-2xl"><label>Durée par défaut des annonces (jours)<input type="number" className={input} value={s.listing_duration_days} onChange={e=>setS({...s,listing_duration_days:e.target.value})}/></label><label>Places maximum dans le formulaire<input type="number" className={input} value={s.max_seats} onChange={e=>setS({...s,max_seats:e.target.value})}/></label><label>Annonces récentes mises en avant<input type="number" className={input} value={s.recent_featured_count} onChange={e=>setS({...s,recent_featured_count:e.target.value})}/></label><label>Durée du badge Nouveau (heures)<input type="number" className={input} value={s.new_badge_hours} onChange={e=>setS({...s,new_badge_hours:e.target.value})}/></label><label>Minimum d’annonces pour comparer les prix<input type="number" className={input} value={s.price_compare_min} onChange={e=>setS({...s,price_compare_min:e.target.value})}/></label><label>Logo du site<select className={input} value={iconChoices.includes(s.site_logo)?s.site_logo:'__custom'} onChange={e=>setS({...s,site_logo:e.target.value==='__custom'?'':e.target.value})}>{iconChoices.map(icon=><option key={icon} value={icon}>{icon}</option>)}<option value="__custom">✍️ Emoji personnalisé</option></select></label><label>Logo personnalisé<input className={input} maxLength={12} placeholder="Ex. 🚀" value={iconChoices.includes(s.site_logo)?'':(s.site_logo||'')} onChange={e=>setS({...s,site_logo:e.target.value})}/></label><h3 className="mt-3 font-black">Textes principaux</h3>{['hero_fr','hero_en','subtitle_fr','subtitle_en'].map(k=><label key={k}>{k}<textarea className={input} value={s.site_texts?.[k]||''} onChange={e=>setS({...s,site_texts:{...s.site_texts,[k]:e.target.value}})}/></label>)}<button className="rounded-xl bg-emerald-400 py-3 font-black text-slate-950"><Save className="mr-2 inline" size={17}/>Enregistrer</button></form></>}
function Backup({backup,setBackup,sections,setSections,exportIt,importIt}){const choices=[['offers','Annonces'],['suggestions','Suggestions'],['alerts','Alertes'],['catalog','Catégories et services'],['settings','Paramètres'],['activity','Journal d’activité']];const toggle=k=>setSections(sections.includes(k)?sections.filter(x=>x!==k):[...sections,k]);return <><h2 className="mb-2 text-2xl font-black">Sauvegarde</h2><p className="mb-5 text-slate-400">Choisis précisément les données à inclure. Les mots de passe, le SMTP et les secrets ne sont jamais exportés.</p><div className="mb-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{choices.map(([k,l])=><label key={k} className="flex cursor-pointer items-center gap-3 rounded-xl border border-slate-800 bg-slate-950/40 p-3"><input type="checkbox" checked={sections.includes(k)} onChange={()=>toggle(k)}/><span className="font-bold">{l}</span></label>)}</div><div className="flex flex-wrap gap-3"><button onClick={exportIt} disabled={!sections.length} className="rounded-xl bg-emerald-400 px-4 py-2 font-black text-slate-950 disabled:opacity-40">Générer la sauvegarde sélectionnée</button><button onClick={()=>navigator.clipboard.writeText(backup)} className={btn}>Copier</button></div><textarea className={`${input} mt-4 min-h-56 font-mono text-xs`} value={backup} onChange={e=>setBackup(e.target.value)} placeholder="GSS2:…"/><button onClick={importIt} className="mt-3 rounded-xl bg-orange-400 px-4 py-2 font-black text-slate-950">Restaurer les éléments présents dans cette sauvegarde</button></>}
function ActivityPanel({data,isSuper,onDelete,onClear}){const rows=data?.activity||[];return <><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-black">Journal d’activité</h2><p className="mt-1 text-sm text-slate-400">{rows.length} activité{rows.length>1?'s':''}</p></div>{isSuper&&rows.length>0&&<button onClick={onClear} className="inline-flex items-center gap-2 rounded-xl border border-red-500/50 px-4 py-2 text-sm font-black text-red-300 hover:bg-red-500/10"><Eraser size={16}/>Vider le journal</button>}</div><div className="space-y-2">{rows.map(a=><div key={a.id} className="flex items-center gap-3 rounded-xl border border-slate-800 p-3"><div className="min-w-0 flex-1"><b>{a.user}</b> · {a.action}{a.details&&Object.keys(a.details).length>0&&<div className="mt-1 text-xs text-slate-400">{Object.entries(a.details).map(([k,v])=>`${k} : ${v}`).join(' · ')}</div>}<div className="text-xs text-slate-500">{new Date(a.at).toLocaleString('fr-FR')}</div></div>{isSuper&&<button onClick={()=>onDelete(a.id)} className={btn} title="Supprimer cette activité"><Trash2 size={15}/></button>}</div>)}{rows.length===0&&<p className="rounded-xl border border-dashed border-slate-700 p-6 text-center text-slate-400">Le journal est vide.</p>}</div></>}
