import { useEffect, useMemo, useState } from 'react'
import { Bell, CheckCircle2, LayoutGrid, List, Moon, Plus, Search, Sun, X } from 'lucide-react'
import { createAlert, createOffer, createSuggestion, getPublicMeta, listOffers, reportOffer, requestAlertManagement } from '../lib/store'
import { detectPlatform, invalidLinkMessage } from '../lib/platform'
import { translations } from '../i18n'
import Modal from '../components/Modal'
import OfferCard from '../components/OfferCard'

const initialForm={link:'',service:'',serviceId:'',plan:'',price:'1.00',seats:1,category:'Autre',platform:'',icon:'📦'}
const initialAlert={email:'',service:'',serviceId:''}
const norm=v=>(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()
const shuffle=a=>[...a].sort(()=>Math.random()-.5)

export default function HomePage(){
 const [offers,setOffers]=useState([]),[meta,setMeta]=useState({catalog:{categories:[],services:[]},settings:{}}),[loading,setLoading]=useState(true)
 const [search,setSearch]=useState(''),[category,setCategory]=useState('Toutes'),[sort,setSort]=useState('recommended'),[view,setView]=useState('grid')
 const [theme,setTheme]=useState(()=>localStorage.getItem('gosharesplit-theme')||'dark'),[lang,setLang]=useState(()=>localStorage.getItem('gosharesplit-lang')||'fr')
 const [modal,setModal]=useState(null),[notice,setNotice]=useState(''),[error,setError]=useState(''),[form,setForm]=useState(initialForm),[alert,setAlert]=useState(initialAlert)
 const [suggestion,setSuggestion]=useState({name:'',category:'Autre',website:'',source:'menu'}),[reporting,setReporting]=useState(null),[reportReason,setReportReason]=useState('no_seats')
 const [manageEmail,setManageEmail]=useState(''),[manageSent,setManageSent]=useState(false),[serviceSeed,setServiceSeed]=useState(0)
 const t=translations[lang]
 useEffect(()=>{document.documentElement.classList.toggle('dark',theme==='dark');document.documentElement.classList.toggle('light',theme==='light');localStorage.setItem('gosharesplit-theme',theme)},[theme])
 useEffect(()=>localStorage.setItem('gosharesplit-lang',lang),[lang])
 async function refresh(){try{const [o,m]=await Promise.all([listOffers(),getPublicMeta()]);setOffers(o);setMeta(m)}finally{setLoading(false)}}
 useEffect(()=>{refresh()},[])
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(id)},[notice])
 const categories=useMemo(()=>['Toutes',...meta.catalog.categories.map(c=>c.name)],[meta])
 const categoryMap=useMemo(()=>Object.fromEntries(meta.catalog.categories.map(c=>[c.id,c])),[meta])
 const services=useMemo(()=>meta.catalog.services.map(s=>({...s,category:categoryMap[s.category_id]?.name||'Autre',icon:s.icon||categoryMap[s.category_id]?.icon||'📦'})),[meta,categoryMap])
 function openModal(name){setModal(name);setError('');setServiceSeed(v=>v+1);if(name==='offer')setForm(initialForm);if(name==='alert')setAlert(initialAlert)}
 function suggestionsFor(query,selectedCategory,limit=14){const q=norm(query).trim();let pool=selectedCategory&&selectedCategory!=='Autre'?services.filter(s=>s.category===selectedCategory):services;if(q)return pool.filter(s=>norm(`${s.name} ${s.category}`).includes(q)).slice(0,limit);const demanded=[...pool].filter(s=>s.active_alerts>0).sort((a,b)=>b.active_alerts-a.active_alerts).slice(0,5);const random=shuffle(pool.filter(s=>!demanded.some(d=>d.id===s.id))).slice(0,limit-demanded.length);return [...demanded,...random]}
 const offerServices=useMemo(()=>suggestionsFor(form.service,form.category,14),[form.service,form.category,services,serviceSeed])
 const alertServices=useMemo(()=>suggestionsFor(alert.service,'Autre',12),[alert.service,services,serviceSeed])
 const popularity=useMemo(()=>Object.fromEntries(services.map(s=>[norm(s.name),Number(s.popularity||0)])),[services])
 const visibleOffers=useMemo(()=>{const q=norm(search);const f=offers.filter(o=>(category==='Toutes'||o.category===category)&&(!q||norm(`${o.service} ${o.plan} ${o.category}`).includes(q)));if(sort==='newest')return [...f].sort((a,b)=>new Date(b.published_at)-new Date(a.published_at));if(sort==='oldest')return [...f].sort((a,b)=>new Date(a.published_at)-new Date(b.published_at));if(sort==='priceAsc')return [...f].sort((a,b)=>a.price-b.price);if(sort==='priceDesc')return [...f].sort((a,b)=>b.price-a.price);if(sort==='seats')return [...f].sort((a,b)=>b.seats-a.seats);const recent=[...f].sort((a,b)=>new Date(b.published_at)-new Date(a.published_at)).slice(0,Number(meta.settings.recent_featured_count||2));const rest=f.filter(x=>!recent.some(r=>r.id===x.id));rest.sort((a,b)=>{const ar=Number(a.reports_count||0),br=Number(b.reports_count||0);if(ar!==br)return ar-br;const ap=popularity[norm(a.service)]||0,bp=popularity[norm(b.service)]||0;if(ap!==bp)return bp-ap;return Math.random()-.5});return [...recent,...rest]},[offers,category,search,sort,popularity,meta])
 function priceLevel(offer){const same=offers.filter(o=>norm(o.service)===norm(offer.service));if(same.length<Number(meta.settings.price_compare_min||4))return'low';const prices=same.map(o=>Number(o.price)).sort((a,b)=>a-b),p=Number(offer.price),low=prices[Math.floor((prices.length-1)/3)],high=prices[Math.ceil((prices.length-1)*2/3)];return p<=low?'low':p>=high?'high':'mid'}
 async function submitOffer(e,force=false){e?.preventDefault();setError('');const detected=detectPlatform(form.link);if(!detected){setError(invalidLinkMessage);return}if(!form.serviceId){setError('Sélectionne un service dans la liste.');return}const same=offers.filter(o=>norm(o.service)===norm(form.service));if(!force&&same.length>=3&&Number(form.price)>Math.max(...same.map(o=>Number(o.price)))){if(!window.confirm('Votre prix est plus élevé que toutes les autres annonces actives pour ce service. Les utilisateurs risquent de privilégier les offres moins chères. Publier quand même ?'))return}await createOffer({...form,service_id:form.serviceId,platform:detected,price:Number(form.price),seats:Number(form.seats)});await refresh();setModal(null);setNotice('Votre annonce a été publiée avec succès.')}
 async function sendReport(){try{await reportOffer(reporting.id,reportReason);await refresh();setReporting(null);setNotice('Signalement enregistré.')}catch(e){setNotice(e.code==='already_reported'?'Vous avez déjà signalé cette annonce.':'Impossible d’enregistrer le signalement.')}}
 const field='w-full rounded-2xl border border-slate-700 bg-slate-950/60 px-4 py-3 outline-none focus:border-emerald-400 light:border-slate-300 light:bg-white'
 return <div className="min-h-screen bg-[#06101d] text-slate-100 light:bg-[#e8edf3] light:text-slate-900">
  {notice&&<div className="fixed left-1/2 top-4 z-[100] flex -translate-x-1/2 items-center gap-2 rounded-2xl bg-emerald-400 px-5 py-3 font-black text-slate-950"><CheckCircle2 size={18}/>{notice}</div>}
  <header className="sticky top-0 z-40 border-b border-white/5 bg-[#06101d]/90 backdrop-blur-xl light:bg-white/90"><div className="mx-auto flex max-w-7xl items-center gap-3 px-4 py-4"><div className="text-xl font-black">GoShareSplit</div><div className="relative ml-auto hidden w-full max-w-md md:block"><Search className="absolute left-3 top-3 text-slate-500" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={t.search} className="w-full rounded-xl border border-slate-700 bg-slate-900 py-2.5 pl-10 pr-3 light:border-slate-300 light:bg-white"/></div><select value={lang} onChange={e=>setLang(e.target.value)} className="control-select"><option value="fr">FR</option><option value="en">EN</option></select><button className="icon-btn" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={18}/>:<Moon size={18}/>}</button></div></header>
  <main className="mx-auto max-w-7xl px-4 py-10"><section className="mb-8 text-center"><h1 className="text-balance text-4xl font-black md:text-6xl">{meta.settings.site_texts?.[`hero_${lang}`]||'Trouvez facilement une place dans un abonnement partagé'}</h1><p className="mx-auto mt-4 max-w-3xl text-slate-400">{meta.settings.site_texts?.[`subtitle_${lang}`]}</p><div className="mt-6 flex flex-wrap justify-center gap-3"><button onClick={()=>openModal('offer')} className="rounded-xl bg-emerald-400 px-5 py-3 font-black text-slate-950"><Plus className="mr-2 inline" size={18}/>{t.add}</button><button onClick={()=>openModal('alert')} className="rounded-xl border border-slate-700 px-5 py-3 font-black"><Bell className="mr-2 inline" size={18}/>{t.alert}</button></div></section>
   <div className="mb-5 md:hidden"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={t.search} className={field}/></div>
   <div className="mb-6 flex flex-wrap gap-2">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={`rounded-full px-4 py-2 text-sm font-bold ${category===c?'bg-emerald-400 text-slate-950':'border border-slate-700'}`}>{c}</button>)}</div>
   <div className="mb-6 flex flex-wrap items-center gap-3"><select value={sort} onChange={e=>setSort(e.target.value)} className="control-select"><option value="recommended">{t.recommended}</option><option value="newest">{t.newest}</option><option value="oldest">{t.oldest}</option><option value="priceAsc">{t.priceAsc}</option><option value="priceDesc">{t.priceDesc}</option><option value="seats">{t.seats}</option></select><div className="ml-auto flex gap-2"><button className="icon-btn" onClick={()=>setView('grid')}><LayoutGrid size={18}/></button><button className="icon-btn" onClick={()=>setView('list')}><List size={18}/></button></div></div>
   {loading?<p>Chargement…</p>:<div className={view==='grid'?'grid gap-5 md:grid-cols-2 xl:grid-cols-3':'grid gap-4'}>{visibleOffers.map(o=><OfferCard key={o.id} offer={o} onReport={setReporting} list={view==='list'} priceLevel={priceLevel(o)} isNew={Date.now()-new Date(o.published_at)<Number(meta.settings.new_badge_hours||24)*3600000} t={t}/>)}</div>}
  </main>
  <footer className="border-t border-white/5 py-8 text-center text-sm text-slate-500"><button onClick={()=>openModal('suggest')} className="font-bold hover:text-emerald-400">Suggérer un service</button></footer>
  {modal==='offer'&&<Modal title={t.add} onClose={()=>setModal(null)}><form onSubmit={submitOffer} className="space-y-4"><label className="label">Lien de partage *</label><input required className={field} value={form.link} onChange={e=>setForm({...form,link:e.target.value,platform:detectPlatform(e.target.value)})}/><label className="label">Catégorie</label><select className={field} value={form.category} onChange={e=>setForm({...form,category:e.target.value,service:'',serviceId:''})}>{meta.catalog.categories.map(c=><option key={c.id}>{c.name}</option>)}</select><label className="label">Service *</label><div className="relative"><input className={field} value={form.service} onChange={e=>setForm({...form,service:e.target.value,serviceId:''})}/>{form.service&&<button type="button" onClick={()=>setForm({...form,service:'',serviceId:''})} className="absolute right-3 top-3 text-red-400"><X size={20}/></button>}</div><div className="flex flex-wrap gap-2">{offerServices.map(s=><button type="button" key={s.id} onClick={()=>setForm({...form,service:s.name,serviceId:s.id,category:s.category,icon:s.icon})} className="rounded-full border border-slate-700 px-3 py-2 text-xs font-bold">{s.name}{s.active_alerts>0&&<span className="ml-1 text-orange-400">🔥{s.active_alerts}</span>}</button>)}</div>{form.serviceId&&<p className="text-sm text-orange-300">🔥 {services.find(s=>s.id===form.serviceId)?.active_alerts||0} alerte(s) active(s) pour ce service</p>}<label className="label">Offre / formule</label><input maxLength={70} className={field} value={form.plan} onChange={e=>setForm({...form,plan:e.target.value})}/><div className="grid grid-cols-2 gap-3"><div><label className="label">Prix / mois (€)</label><input type="number" min="0.01" step="0.01" className={field} value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></div><div><label className="label">Places</label><input type="number" min="1" max={meta.settings.max_seats||20} className={field} value={form.seats} onChange={e=>setForm({...form,seats:e.target.value})}/></div></div>{error&&<p className="text-sm font-bold text-red-400">{error}</p>}<button className="w-full rounded-xl bg-emerald-400 py-3 font-black text-slate-950">Publier l’annonce</button></form></Modal>}
  {modal==='alert'&&<Modal title={t.alert} onClose={()=>setModal(null)}><form onSubmit={async e=>{e.preventDefault();await createAlert({email:alert.email,service:alert.service,service_id:alert.serviceId});setModal(null);setNotice('Alerte enregistrée.')}} className="space-y-4"><label className="label">E-mail *</label><input required type="email" className={field} value={alert.email} onChange={e=>setAlert({...alert,email:e.target.value})}/><label className="label">Service *</label><input className={field} value={alert.service} onChange={e=>setAlert({...alert,service:e.target.value,serviceId:''})}/><div className="flex flex-wrap gap-2">{alertServices.map(s=><button type="button" key={s.id} onClick={()=>setAlert({...alert,service:s.name,serviceId:s.id})} className="rounded-full border border-slate-700 px-3 py-2 text-xs font-bold">{s.name}</button>)}</div><button disabled={!alert.serviceId} className="w-full rounded-xl bg-emerald-400 py-3 font-black text-slate-950 disabled:opacity-40">Créer l’alerte</button></form><button onClick={()=>setModal('manage')} className="mt-4 w-full text-sm font-bold text-emerald-400">Déjà inscrit ? Gérer mes alertes</button></Modal>}
  {modal==='manage'&&<Modal title="Gérer mes alertes" onClose={()=>setModal(null)}><form onSubmit={async e=>{e.preventDefault();await requestAlertManagement(manageEmail);setManageSent(true)}} className="space-y-4"><input required type="email" className={field} value={manageEmail} onChange={e=>setManageEmail(e.target.value)} placeholder="votre@email.fr"/><button className="w-full rounded-xl bg-emerald-400 py-3 font-black text-slate-950">Recevoir mon lien sécurisé</button>{manageSent&&<p className="text-sm text-emerald-300">Si cette adresse possède des alertes, le lien a été envoyé.</p>}</form></Modal>}
  {modal==='suggest'&&<Modal title="Suggérer un service" onClose={()=>setModal(null)}><form onSubmit={async e=>{e.preventDefault();await createSuggestion(suggestion);setModal(null);setNotice('Suggestion envoyée.')}} className="space-y-4"><input required className={field} placeholder="Nom du service" value={suggestion.name} onChange={e=>setSuggestion({...suggestion,name:e.target.value})}/><select className={field} value={suggestion.category} onChange={e=>setSuggestion({...suggestion,category:e.target.value})}>{meta.catalog.categories.map(c=><option key={c.id}>{c.name}</option>)}</select><input className={field} placeholder="URL ou indication (optionnel)" value={suggestion.website} onChange={e=>setSuggestion({...suggestion,website:e.target.value})}/><button className="w-full rounded-xl bg-emerald-400 py-3 font-black text-slate-950">Envoyer</button></form></Modal>}
  {reporting&&<Modal title={t.reportTitle} onClose={()=>setReporting(null)}><div className="space-y-3">{[['no_seats',t.noSeats],['invalid_link',t.invalidLink],['wrong_info',t.wrongInfo]].map(([v,l])=><label key={v} className="flex items-center gap-3 rounded-xl border border-slate-700 p-3"><input type="radio" checked={reportReason===v} onChange={()=>setReportReason(v)}/>{l}</label>)}<button onClick={sendReport} className="w-full rounded-xl bg-red-500 py-3 font-black text-white">{t.submitReport}</button></div></Modal>}
 </div>
}
